import type { Prescription } from "@/types/pharmacy.type";

export const initialPrescriptions: Prescription[] = [
  {
    id: "RX-001",
    date: "2026-04-01",
    patientName: "Pham Thi Dung",
    phone: "0945678901",
    doctor: "BS. Nguyen Thi Lan",
    insuranceNumber: "HP3456789012345",
    diagnosis: "Kham thai dinh ky",
    treatment: "Bo sung vi chat va tai kham theo lich hen",
    prescriptionItems: [
      {
        medicationId: "M-001",
        medicationName: "Vitamin tong hop",
        dosage: "500mg",
        unit: "vien",
        quantity: 30,
        price: 5000,
        usage: "Uong 1 vien/ngay sau an",
      },
      {
        medicationId: "M-002",
        medicationName: "Canxi",
        dosage: "600mg",
        unit: "vien",
        quantity: 30,
        price: 6000,
        usage: "Uong 1 vien/ngay buoi toi",
      },
    ],
    totalMedicationCost: 330000,
    status: "pending",
  },
  {
    id: "RX-002",
    date: "2026-04-01",
    patientName: "Nguyen Van An",
    phone: "0912345678",
    doctor: "BS. Nguyen Van Hung",
    insuranceNumber: "",
    diagnosis: "Dau dau keo dai",
    treatment: "Theo doi huyet ap va nghi ngoi",
    prescriptionItems: [
      {
        medicationId: "M-003",
        medicationName: "Paracetamol",
        dosage: "500mg",
        unit: "vien",
        quantity: 10,
        price: 1500,
        usage: "Uong 2 vien/ngay sau an",
      },
    ],
    totalMedicationCost: 15000,
    status: "pending",
  },
  {
    id: "RX-003",
    date: "2026-03-31",
    patientName: "Le Minh Cuong",
    phone: "0934567890",
    doctor: "BS. Tran Thi Mai",
    insuranceNumber: "",
    diagnosis: "Viem hong cap",
    treatment: "Uong thuoc dung lieu va giu am co hong",
    prescriptionItems: [
      {
        medicationId: "M-004",
        medicationName: "Amoxicillin",
        dosage: "500mg",
        unit: "vien",
        quantity: 14,
        price: 2500,
        usage: "Uong 2 vien/ngay sau an",
      },
    ],
    totalMedicationCost: 35000,
    status: "dispensed",
    serviceFee: 50000,
    insuranceDiscount: 0,
    totalAmount: 85000,
  },
];
