import type { Appointment, Medicine } from "./types";

export const mockAppointments: Appointment[] = [
  {
    id: 1,
    patient: {
      id: 101,
      full_name: "Pham Thi Dung",
      date_of_birth: "1995-03-25",
      phone_number: "0945678901",
      hometown: "Hai Phong",
      national_id: "001095012345",
      insurance_number: "HP3456789012345",
      gender: "female",
    },
    doctor_name: "BS. Nguyen Thi Lan",
    symptoms: "Kham thai 3 thang",
    scheduled_date: "2026-04-01",
    scheduled_time: "09:00",
    queue_number: 1,
    appointment_time: "09:00 01/04/2026",
    status: "confirmed",
  },
  {
    id: 2,
    patient: {
      id: 102,
      full_name: "Nguyen Van An",
      date_of_birth: "1985-05-15",
      phone_number: "0912345678",
      hometown: "Ha Noi",
      national_id: "001085012345",
      insurance_number: "DN1234567890123",
      gender: "male",
    },
    doctor_name: "BS. Nguyen Van Hung",
    symptoms: "Dau dau, chong mat, buon non keo dai 3 ngay",
    scheduled_date: "2026-04-01",
    scheduled_time: "10:30",
    queue_number: 2,
    appointment_time: "09:30 01/04/2026",
    status: "confirmed",
  },
  {
    id: 3,
    patient: {
      id: 103,
      full_name: "Le Minh Cuong",
      date_of_birth: "1978-12-10",
      phone_number: "0934567890",
      hometown: "Da Nang",
      national_id: "001078012345",
      insurance_number: "",
      gender: "male",
    },
    doctor_name: "BS. Tran Thi Mai",
    symptoms: "Ho, sot nhe, dau hong",
    scheduled_date: "2026-03-31",
    scheduled_time: "08:00",
    queue_number: 3,
    appointment_time: "08:00 31/03/2026",
    status: "completed",
    diagnosis: "Viem hong cap",
    doctor_advice: "Nghi ngoi, giu am hong, tai kham sau 3 ngay neu khong do.",
    prescription_items: [
      {
        medicine_id: 1,
        quantity: 10,
        usage_instructions: "Uong 2 vien/ngay sau an",
        medicine: {
          id: 1,
          medicine_name: "Paracetamol",
          dosage: "500mg",
          category: "Giam dau - Ha sot",
          unit: "vien",
          stock_quantity: 120,
          selling_price: 1500,
        },
      },
    ],
    total_medicine_cost: 15000,
  },
];

export const mockMedicines: Medicine[] = [
  {
    id: 1,
    medicine_name: "Paracetamol",
    dosage: "500mg",
    category: "Giam dau - Ha sot",
    unit: "vien",
    stock_quantity: 120,
    selling_price: 1500,
  },
  {
    id: 2,
    medicine_name: "Amoxicillin",
    dosage: "500mg",
    category: "Khang sinh",
    unit: "vien",
    stock_quantity: 80,
    selling_price: 2500,
  },
  {
    id: 3,
    medicine_name: "Vitamin C",
    dosage: "1000mg",
    category: "Vitamin",
    unit: "vien",
    stock_quantity: 200,
    selling_price: 1000,
  },
  {
    id: 4,
    medicine_name: "Siro ho",
    dosage: "100ml",
    category: "Ho - Hong",
    unit: "chai",
    stock_quantity: 25,
    selling_price: 35000,
  },
  {
    id: 5,
    medicine_name: "Cetirizine",
    dosage: "10mg",
    category: "Di ung",
    unit: "vien",
    stock_quantity: 60,
    selling_price: 1800,
  },
];
