spring.application.name=demo
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=KLTN;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Sa@123456

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# # Gemini API (free tier)
# ai.gemini.enabled=true
# ai.gemini.api-key=${GEMINI_API_KEY:dummy-gemini-key}
# ai.gemini.model=gemini-2.5-flash-lite
# ai.gemini.endpoint=https://generativelanguage.googleapis.com/v1beta/models
# ai.gemini.timeout-seconds=20

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=butlop1503@gmail.com
spring.mail.password=mnacapikvegjxkkx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Danh sach email le tan nhan thong bao dat lich moi (cach nhau boi dau phay)
# clinic.notification.receptionist.emails=${RECEPTIONIST_NOTIFICATION_EMAILS:${RECEPTIONIST_NOTIFICATION_EMAIL:}}
clinic.notification.receptionist.emails=butlop1503@gmail.com

server.port=8081
